### ISSUE TITLE
Field Array validation not working as expected

### ISSUE THREAD

**Issue by davidhenley** [final-form/react-final-form-arrays#3]
@erikras 

As you can see the validation is returning correctly, but the form errors are not showing for the field array.

Try typing in a first name.

Also try adding 6 customers, each with just a last name. You only get 3 form errors

[![Edit 🏁 React Final Form - Field Arrays](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xvrv30p95q)

**Comment by davidhenley** [comment]
@erikras Still not working correctly in 1.0.1

**Comment by erikras** [comment]
Yep, that's a bug. Thanks!

**Comment by davidhenley** [comment]
Formik's FieldArray has the same issue right now. Array validation seems to be a tricky thing. Redux-Form is the only react form tool that handles these gracefully.

**Comment by erikras** [comment]
Fix published in [`final-form@1.3.3`](https://github.com/final-form/final-form/releases/tag/v1.3.3).

**Comment by erikras** [comment]
Hmm.. Seems to not be fixed in your sandbox... Reopening....

**Comment by erikras** [comment]
Something went wrong in the publishing of `v1.3.3`. Fixed in [`v1.3.4`](https://github.com/final-form/final-form/releases/tag/v1.3.4).

One thing, if your array is full of objects, you need to push an object.
```jsx
push('customers', undefined) // ❌

push('customers', {}) // ✅
```

**Comment by davidhenley** [comment]
Still not working for me. Am I doing this wrong?

```
const productValidate = values => {
  const errorArray = [];

  values.forEach(value => {
    const errors = {};

    if (!values.cases && !value.bottles) {
      errors.cases = 'Quantity Required';
      errors.bottles = 'Quantity Required';
    }

    errorArray.push(errors);
  });

  return errorArray;
}
```
```
{
  "values": {
    "products": [
      {
        "placeholder": null,
        "cases": "3"
      }
    ]
  },
  "errors": {
    "customer": "Required",
    "manager": "Required",
    "reason": "Required",
    "deliveredBy": "Required",
    "date": "Required",
    "location": "Required",
    "products": [
      {
        "cases": "Quantity Required",
        "bottles": "Quantity Required"
      }
    ]
  }
}
```

**Comment by davidhenley** [comment]
My meta.error is still undefined for any item in the field array, even though the form errors are working correctly.

**Comment by erikras** [comment]
Show updated sandbox?

**Comment by davidhenley** [comment]
OK. Working on it now.

**Comment by davidhenley** [comment]
Yep. Here it is. Showing null for error. Also, try adding 3-4 customers with last names. and look at form errors.

[![Edit RFF Field Array Problem](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xvrv30p95q)

**Comment by erikras** [comment]
I'm not seeing the `null` error. Is it being displayed somewhere?

I did find another bug from this sandbox, though, so thanks for that.

**Comment by davidhenley** [comment]
@erikras it's in the console.

**Comment by erikras** [comment]
Duh. 🙄🤦‍♂️

Okay, escalating this issue back to "bug" status.

**Comment by erikras** [comment]
Published fix in [`v1.3.5`](https://github.com/final-form/final-form/releases/tag/v1.3.5).

**Comment by davidhenley** [comment]
Verified. Thank you for all your help!

**Comment by erikras** [comment]
And thank you for kicking the tires! 👍

**Comment by davidhenley** [comment]
One last thing and I might can get around this, but if my FieldArray error object is an array with an empty object, then the form is marking as invalid. Do you know the best way around this?

**Comment by davidhenley** [comment]
One thing to note, is if the array is full of empty objects, you need to return undefined in the validate.

My validate function now looks like this:

```
const productValidate = values => {
  const errorArray = [];

  values.forEach(value => {
    const errors = {};

    if (!value.name) errors.name = 'Required';
    if (!value.cases && !value.bottles) {
      errors.cases = 'Required';
      errors.bottles = 'Required';
    }
    if (!value.billback) errors.billback = 'Required';

    errorArray.push(errors);
  });

  if (errorArray.some(object => !isEmpty(object))) {
    return errorArray;
  } else {
    return undefined;
  }
}
```

**Comment by huygn** [comment]
Yea I have the same concern as above, the array validate must keeps empty objects to ensure error message goes into the correct array field. I ended up with not using `onSubmit` and write `isValid(errors)` for my custom submit method, feels really dirty :/.

**Comment by davidhenley** [comment]
Yeah, I tried to return undefined for each item, then realized the errors weren't mapping anymore. Mine isn't that bad. I mean the only thing I think that @erikras could do is use the same some function to check if all items are empty then return undefined if they are.
